spring.application.name=limebank
spring.datasource.url=jdbc:postgresql://localhost:5432/limebank
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.flyway.enabled=true
debug=true
logging.level.org.springframework=DEBUG

// fake secret, only for development
JWT_SECRET="87b6bdfe-44fe-4336-a668-b08133c18f64"

server.port=8000